### ISSUE TITLE
Publish to Maven Central/JCenter?

### ISSUE THREAD

**Issue by jbarr21** [Commit451/ResourcesPoet#5]
Would it be possible for you to publish artifacts to Maven Central or JCenter? Otherwise, users of libraries that depend on this library are forced to add Jitpack as a repo, which is a poor experience and they may have policies not allowing this.

**Comment by Jawnnypoo** [comment]
Hey! It is more just due to the fact that JitPack allow for really easy and simple releases. While I value Maven Central/JCenter, I don't think there are any plans to release to it at this time.

**Comment by Jawnnypoo** [comment]
@jbarr21 I see this is now used in https://github.com/uber/stylist

Neat library! If I were to deploy on jcenter, would you guys be able to do a direct dependency on this lib instead of repackaging it?

**Comment by jbarr21** [comment]
thanks! yep, that would be great

**Comment by jbarr21** [comment]
if this might happen, can you please re-open the issue so that I can track it?

**Comment by Jawnnypoo** [comment]
Okay, this is now done for 2.1.0

```
api com.commit451:resourcespoet:2.1.0
```
