### ISSUE TITLE
Setting indent to true does not indent generated resources

### ISSUE THREAD

**Issue by jbarr21** [Commit451/ResourcesPoet#6]
[I had to add](https://github.com/uber/stylist/blob/master/resources-poet/src/main/kotlin/com/commit451/uresourcespoet/ResourcesPoet.kt#L524) `transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "2")` after setting the `OutputKey.INDENT`.

**Comment by Jawnnypoo** [comment]
Sweet, I'll be sure to add this 😄

**Comment by jbarr21** [comment]
i'm can submit a PR. the test fixtures will need updating, as well

**Comment by Jawnnypoo** [comment]
That sounds good to me, if you have the time 👍
